/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class BaseProductosSuperDelBarrio extends javax.swing.JFrame {
   conexionMysql conec = new conexionMysql(); //llamado de clase
   Connection conectar = conec.getConnection(); // llamado de conexion
    /**
     * Creates new form BaseProductosSuperDelBarrio
     */
    public BaseProductosSuperDelBarrio() {
        initComponents();
        Consultar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(51, 51, 255)));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoproductoID", "MarcaProducto", "NombreProducto", "DescripcionProducto", "CantidadDisponibleProducto"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 255, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 760, 210));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Codigo del producto ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 200, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Marca del producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre del producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripcion del producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cantidad disponible del producto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, 20));

        btnNuevo.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevo.setText("Agregar nuevo dato");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 30));

        btnModificar.setBackground(new java.awt.Color(255, 255, 204));
        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Editar dato");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 140, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar dato");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, 30));

        btnConsultar.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar estado de la tabla");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 230, 30));

        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 310, -1));

        txtMarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 310, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 310, -1));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 310, -1));

        txtCantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 310, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/icono.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        btnExportar.setBackground(new java.awt.Color(255, 153, 153));
        btnExportar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportar.setText("Exportar datos");
        btnExportar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 230, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/Union.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    Guardar();
        txtCodigo.setText("");
        txtMarca.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtCantidad.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     Borrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    Consultar("");
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
    GestionDeTabla();    
    }//GEN-LAST:event_TablaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ModificarDatos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
          DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();

        // Llama al método generarPDF aquí
        generarPDF(modelo, "productos.pdf");
         
    }//GEN-LAST:event_btnExportarActionPerformed

 public void Consultar(String NombreProducto){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CodigoproductoID");
    modelo.addColumn("MarcaProducto");
    modelo.addColumn("NombreProducto");    
    modelo.addColumn("DescripcionProducto");
    modelo.addColumn("CantidadDisponibleProducto");
    Tabla.setModel(modelo);
    String sql="";
    if(NombreProducto.equals("")){
        sql="Select*from producto";
    }else{
        sql="Select*from producto where NombreProducto like'%"+NombreProducto+"%'";
    }
    String producto[]=new String[5];
    Statement set;
    try {
        set = conectar.createStatement(); 
        ResultSet resul=set.executeQuery(sql);
        while(resul.next()){
              producto[0]=resul.getString(1);
              producto[1]=resul.getString(2);
              producto[2]=resul.getString(3);  
              producto[3]=resul.getString(4);
              producto[4]=resul.getString(5);
                  modelo.addRow(producto);        
        }
        Tabla.setModel(modelo);
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"El error es:"+ex);
        
    }
}
 public void Guardar(){
     String CodigoproductoID = txtCodigo.getText();
     String MarcaProducto = txtMarca.getText();
     String NombreProducto = txtNombre.getText();
     String DescripcionProducto = txtDescripcion.getText();
     String CantidadDisponibleProducto =txtCantidad.getText();
     
     
     String Sql="Insert into producto() Values(?,?,?,?,?)";
    try {
        Statement set= conectar.createStatement();
        ResultSet resultado = set.executeQuery("Select*from producto where CodigoproductoID like'"+txtCodigo.getText()+"'");
        if(resultado.next()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Usuario ya existe");
            txtCodigo.requestFocus();
        }else if(txtCodigo.getText().isEmpty()){
             getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Identidad Obligatoria");
            txtCodigo.requestFocus();
        }else{
            PreparedStatement pasar =conectar.prepareStatement(Sql);
            pasar.setString(1, CodigoproductoID);
            pasar.setString(2, MarcaProducto);
            pasar.setString(3, NombreProducto);
            pasar.setString(4, DescripcionProducto);
            pasar.setString(5, CantidadDisponibleProducto);
            pasar.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro Exitoso");
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"El error es:"+ex);
    }
     
 }
 public void GestionDeTabla(){
     int fila=Tabla.getSelectedRow();
     if(fila>=0){
         txtCodigo.setText(Tabla.getValueAt(fila,0).toString());
          txtMarca.setText(Tabla.getValueAt(fila,1).toString());
           txtNombre.setText(Tabla.getValueAt(fila,2).toString());
            txtDescripcion.setText(Tabla.getValueAt(fila,3).toString());
             txtCantidad.setText(Tabla.getValueAt(fila,4).toString());
     }else{
         JOptionPane.showMessageDialog(null,"No se selecciono fila");
     }
 }
 public void ModificarDatos(){
    try {
        PreparedStatement pasar = conectar.prepareStatement("Update producto set MarcaProducto ='"+txtMarca.getText()+"',NombreProducto ='"+txtNombre.getText()+"',DescripcionProducto='"+txtDescripcion.getText()
                +"',CantidadDisponibleProducto='"+txtCantidad.getText()+"' where CodigoproductoID='"+txtCodigo.getText()+"'");
        pasar.executeUpdate();
        Consultar("");
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"El error es:"+ex);
    }
 }
 public void Borrar(){
    int fila=Tabla.getSelectedRow();
    String CodigoproductoID =Tabla.getValueAt(fila,0).toString();
    int n=JOptionPane.showConfirmDialog(null,"Desea eliminar registro","Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
    if(n==JOptionPane.YES_NO_OPTION){
    try {
        PreparedStatement borrar=conectar.prepareStatement("Delete from producto where CodigoproductoID ='"+CodigoproductoID+"'");
        borrar.executeUpdate();
        Consultar("");
    } catch (SQLException ex) {
      JOptionPane.showConfirmDialog(null,"Desea eliminar registro"+ex);
    }
    }
}   
 public void generarPDF(DefaultTableModel modelo, String nombreArchivo) {
    Document documento = new Document();

    try {
        PdfWriter.getInstance(documento, new FileOutputStream(nombreArchivo));
        documento.open();

        PdfPTable tabla = new PdfPTable(modelo.getColumnCount());

        // Encabezados de la tabla
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            tabla.addCell(modelo.getColumnName(i));
        }

        // Datos de la tabla
        for (int fila = 0; fila < modelo.getRowCount(); fila++) {
            for (int columna = 0; columna < modelo.getColumnCount(); columna++) {
                tabla.addCell(modelo.getValueAt(fila, columna).toString());
            }
        }

        documento.add(tabla);
        documento.close();

        JOptionPane.showMessageDialog(null, "PDF generado exitosamente en: " + nombreArchivo);
    } catch (DocumentException | IOException e) {
        // Manejo de excepciones
        e.printStackTrace(); // Esto imprimirá la traza del error, puedes personalizarlo
        JOptionPane.showMessageDialog(null, "Error al generar el PDF: " + e.getMessage());
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseProductosSuperDelBarrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseProductosSuperDelBarrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseProductosSuperDelBarrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseProductosSuperDelBarrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseProductosSuperDelBarrio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
